repos:
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        stages: [commit]
-   repo: https://github.com/pycqa/flake8
    rev: '3.8.4'
    hooks:
    -   id: flake8
        additional_dependencies:
          - "flake8-builtins"
          - "flake8-import-order"
        stages: [commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        stages: [commit]
exclude: 'tests'